name: labeler

on:
    pull_request:

jobs:
    team-labeler:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: equitybee/team-label-action@main
              with:
                  repo-token: ${{ secrets.TEAMS_ADMINS }}
                  organization-name: BMSTU-Schedule